---
- name: Update & Upgrade
  hosts: hosts
  become: true
  tasks:
        - name: Update
          apt:
            update_cache: yes
        - name: Install Dependencies
          apt:
            name:
              - make
              - apt-transport-https   
              - ca-certificates
              - curl
              - software-properties-common
              - python3-pip
              - virtualenv
              - python3-setuptools
            state: latest
            
        - name: Add Docker GPG apt Key
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker Repository
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu focal stable
            state: present

        - name: Update apt and install docker-ce
          apt:
            name: docker-ce
            state: latest
            update_cache: true

        - name: Install Docker Module for Python
          pip:
            name: docker

        - name: Enable Docker service to start on boot
          systemd:
            name: docker
            enabled: yes
            state: started

        - name: Add the current user to the docker group
          user:
            name: "{{ ansible_user }}"
            groups: docker
            append: yes
            state: present

        - name: Copy Inception folder to remote
          copy:
            src: ./Inception
            dest: .


        # - name: Run Inception
        #   shell: |
        #     cd Inception && make
