- name: Clean up
  hosts: hosts
  become: true
  tasks:
    - name: Shutdown running container
      shell: |
        cd inception
        make clean clean_volumes
        cd .. && rm -rf inception data
        docker system prune -af