---
- name: Application Deployment (Inception)
  hosts: hosts
  become: true
  tasks:
    - name: Copy Inception folder to remote
      copy:
        src: ../inception
        dest: .
      tags:
      - copy
      
    - name: Run Inception
      shell: |
        cd inception/
        make re
