---
- name: Application Deployment (Inception)
  hosts: hosts
  become: true
  tasks:
    - name: Copy Inception folder to remote
      copy:
        src: ../inception
        dest: .
      tags:
      - copy

    - name: Create volume folders
      file:
        path: "./data/{{ item }}"
        state: directory
        recurse: true
        owner: "{{ ansible_user }}"
      with_items:
        - database
        - site-files
        - influxdb
      tags:
        - volumes

    - name: Edit DOMAIN ENV value
      lineinfile:
        path: /{{ ansible_user }}/inception/srcs/.env
        regexp: '^DOMAIN='
        line: "DOMAIN={{ hostvars[inventory_hostname]['ansible_eth1']['ipv4']['address'] }}"
      
    - name: Run Inception
      shell: |
        cd inception/
        make re
      tags:
        - run