---
- name: System Update & Install Dependencies
  hosts: hosts
  become: true
  tasks:
    - name: Update system
      apt:
        update_cache: yes

    - name: Install necessary packages
      apt:
        name:
          - make
          - apt-transport-https   
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
  tags:
    - apt